### ISSUE TITLE
有没有luci?

### ISSUE THREAD

**Issue by chancat87** [pexcn/openwrt-chinadns-ng#10]
你好作者,编译这个应用会一起生成luci界面么?

**Comment by freeskyfly** [comment]
我自己做了一个或许你可以试试？
链接: https://pan.baidu.com/s/1w3341tJDFz5zCBXwiCxhUg 提取码: abba 
里面包含连个lua文件，下载后覆盖到路由器的/usr/lib/lua/ 文件夹
重启/etc/init.d/uhttpd restart
![image](https://user-images.githubusercontent.com/14343603/74083719-4b7f1b00-4aa2-11ea-9c32-32c9a2eea488.png)

**Comment by pexcn** [comment]
没有 luci 界面，手动调整 `/etc/config/chinadns-ng` 这个配置文件就行了。

**Comment by chancat87** [comment]
> 我自己做了一个或许你可以试试？
> 链接: https://pan.baidu.com/s/1w3341tJDFz5zCBXwiCxhUg 提取码: abba
> 里面包含连个lua文件，下载后覆盖到路由器的/usr/lib/lua/ 文件夹
> 重启/etc/init.d/uhttpd restart
> ![image](https://user-images.githubusercontent.com/14343603/74083719-4b7f1b00-4aa2-11ea-9c32-32c9a2eea488.png)

多谢分享,回家试试..固件不同有影响么 不知道..我是x86_64的
然后看你截图 发现这个 ![image](https://s2.ax1x.com/2020/02/09/1W7FT1.png) 6啊 这是不是就可以配合smartdns配置国内国外dns解析了哦

**Comment by freeskyfly** [comment]
luci应该跟固件没什么关系的。我编译了一个ipk，这样会比较容易。
关于用法建议你还是看下https://github.com/zfl9/chinadns-ng 这个项目的介绍。总的来说就是国内的dns填国内可信的dns，可信的dns填国外的dns，当然你要能保证国外的dns你的访问路径不会被污染，我是配合https-dns-proxy。这个项目openwrt的源上就有，它可以通过http是访问几个dns。
另外记得做个脚本把几个路由文件更新下。
链接: https://pan.baidu.com/s/117wnMs2OL1oxOrhjDItUFQ 提取码: ydeq 
![image](https://user-images.githubusercontent.com/14343603/74090346-295abc80-4ae5-11ea-942b-e0333d2c3e4a.png)

**Comment by chancat87** [comment]
> luci的应该跟固件没什么关系的。我编译了一个IPK，这样会比较容易。
> 关于用法英语谚语建议你还是看下https://github.com/zfl9/chinadns-ng这个项目的介绍。总的来说就是国内的dns填入国内可信的dns，可信的dns填入国外的dns，当然你要能保证国外的dns你的访问路径不会被污染，我是配合https-dns-proxy。这个项目openwrt的源上还有
> 记得做个脚本把几个路由文件更新下。
> 链接：[https](https://pan.baidu.com/s/117wnMs2OL1oxOrhjDItUFQ) ://pan.baidu.com/s/117wnMs2OL1oxOrhjDItUFQ提取代码：ydeq
> ![图片](https://user-images.githubusercontent.com/14343603/74090346-295abc80-4ae5-11ea-942b-e0333d2c3e4a.png)

多谢回复，很棒…

**Comment by chancat87** [comment]
> 我自己做了一个或许你可以试试？
> 链接: https://pan.baidu.com/s/1w3341tJDFz5zCBXwiCxhUg 提取码: abba
> 里面包含连个lua文件，下载后覆盖到路由器的/usr/lib/lua/ 文件夹
> 重启/etc/init.d/uhttpd restart
> ![image](https://user-images.githubusercontent.com/14343603/74083719-4b7f1b00-4aa2-11ea-9c32-32c9a2eea488.png)

咦…你这个文件取消分享了……能再发一下嘛…😂，刚到家里准备设置看看的

**Comment by chancat87** [comment]
> 没有 luci 界面，手动调整 `/etc/config/chinadns-ng` 这个配置文件就行了。

谢谢你😊

**Comment by yubanmeiqin9048** [comment]
> 我自己做了一个或许你可以试试？
> 链接: https://pan.baidu.com/s/1w3341tJDFz5zCBXwiCxhUg 提取码: abba
> 里面包含连个lua文件，下载后覆盖到路由器的/usr/lib/lua/ 文件夹
> 重启/etc/init.d/uhttpd restart
> ![image](https://user-images.githubusercontent.com/14343603/74083719-4b7f1b00-4aa2-11ea-9c32-32c9a2eea488.png)

文件失效了
