### ISSUE TITLE
关于 LuCI

### ISSUE THREAD

**Issue by pexcn** [pexcn/openwrt-chinadns-ng#12]
假如需要使用 LuCI 用户界面，可以参考以下链接：
- https://github.com/pexcn/openwrt-chinadns-ng/tree/luci
- https://github.com/pexcn/openwrt-chinadns-ng/issues/11
- https://github.com/pexcn/openwrt-chinadns-ng/issues/10
- https://github.com/pexcn/openwrt-chinadns-ng/issues/8

**Comment by openwrtdiy** [comment]
新luci-app-chinadns-ng 界面上的规则更新，需要在openwrt-chinadns-ng包里默认集成wget

define Package/chinadns-ng
	SECTION:=net
	CATEGORY:=Network
	TITLE:=ChinaDNS Next Generation, refactoring with epoll and ipset
	URL:=https://github.com/zfl9/chinadns-ng
	DEPENDS:=+ipset +wget
endef

**Comment by openwrtdiy** [comment]
OpenWrt-19.07.6-LUCI界面上显示大部分英文
![下载](https://user-images.githubusercontent.com/57249132/105636024-fbb47380-5e1a-11eb-860d-c0199c88954f.png)

**Comment by openwrtdiy** [comment]
@pexcn 

更新源码之后 https://github.com/pexcn/openwrt-chinadns-ng/commit/19b325c29338699af471cd70444b8f203b57fc98
请更新增加luci-app-chinadns-ng界面上相应的no_ipv6开关选项

**Comment by pexcn** [comment]
https://github.com/pexcn/openwrt-chinadns-ng/issues/11#issuecomment-584488759
luci 分支不是我维护的

**Comment by zhihuiyuze** [comment]
您好
make: *** [/home/zhyz/openwrt-sdk-19.07.6-x86-64_gcc-7.5.0_musl.Linux-x86_64/include/toplevel.mk:220: package/luci-app-chinadnsng/clean] Error 2
我搜索了也没找到luci-app-chinadns-ng

**Comment by pexcn** [comment]
> 您好
> make: *** [/home/zhyz/openwrt-sdk-19.07.6-x86-64_gcc-7.5.0_musl.Linux-x86_64/include/toplevel.mk:220: package/luci-app-chinadnsng/clean] Error 2
> 我搜索了也没找到luci-app-chinadns-ng

make package/luci-app-chinadns-ng/{clean,compile} V=s

**Comment by jliveusa** [comment]
luci会跟进chinadns-ng的更新吗？
