### ISSUE TITLE
将CHINADNS-NG编译好后如何设置和openwrt启动项？我编译好固件后发现ChinaDNS并没有自动运行

### ISSUE THREAD

**Issue by yubanmeiqin9048** [pexcn/openwrt-chinadns-ng#18]
还有一个问题是，将luci页面编译进去后，我并没有在openwrt页面里面找到相应的CHINADNS NG的LUCI

**Comment by pexcn** [comment]
确保 `/etc/config/chinadns-ng` 的 `enable` 设置为 `1`

**Comment by yubanmeiqin9048** [comment]
> 确保 `/etc/config/chinadns-ng` 的 `enable` 设置为 `1`

里面没有这个文件

**Comment by pexcn** [comment]
https://github.com/pexcn/openwrt-chinadns-ng/blob/master/files/chinadns-ng.config#L3
https://github.com/pexcn/openwrt-chinadns-ng/blob/master/Makefile#L49

如果没有，就是没有安装

**Comment by yubanmeiqin9048** [comment]
> https://github.com/pexcn/openwrt-chinadns-ng/blob/master/files/chinadns-ng.config#L3
> https://github.com/pexcn/openwrt-chinadns-ng/blob/master/Makefile#L49
> 
> 如果没有，就是没有安装

我在系统软件包里面看到了CHINADNS NG和LUCI APP CHINADNS NG

**Comment by pexcn** [comment]
那就不清楚了，我没有遇到过这个问题。

**Comment by yubanmeiqin9048** [comment]
> 那就不清楚了，我没有遇到过这个问题。

是不是因为我安装了PASSWALL，而PASSWALL里内置了ChinaDNS NG所以才会这样。。。。
如果我把PASSWALL内置的ChinaDNS ng删除是不是应该就会正常了

**Comment by pexcn** [comment]
不知道

**Comment by zoverdoser** [comment]
同样遇到chinadns-ng没有自动启动的问题, 也没有生成/etc/config/chinadns-ng配置文件
ssh连上去手动chinadns-ng可以运行 @yubanmeiqin9048 后来有解决么?

**Comment by GaranTaburiss** [comment]
> > https://github.com/pexcn/openwrt-chinadns-ng/blob/master/files/chinadns-ng.config#L3
> > https://github.com/pexcn/openwrt-chinadns-ng/blob/master/Makefile#L49
> > 如果没有，就是没有安装
> 
> 我在系统软件包里面看到了CHINADNS NG和LUCI APP CHINADNS NG

PASSWALL的依赖里也有个chinadns-ng，编译的时候就会走他那里面的makefile
