### ISSUE TITLE
如何编译出mips_24kc的ipk呢

### ISSUE THREAD

**Issue by zeroly** [pexcn/openwrt-chinadns-ng#23]
您好，
    请教一下如何编译出mips_24kc的ipk呢，默认编译出来的包是chinadns-ng_1.0-beta.23-1_ar71xx.ipk，无法在我的NETGEAR WNDR3800上运行，好像是34kc的？
我的设备信息如下：
```
root@OpenWrt:/tmp# cat /proc/cpuinfo
system type		: Atheros AR7161 rev 2
machine			: NETGEAR WNDR3700/WNDR3800/WNDRMAC
processor		: 0
cpu model		: MIPS 24Kc V7.4
BogoMIPS		: 452.19
wait instruction	: yes
microsecond timers	: yes
tlb_entries		: 16
extra interrupt vector	: yes
hardware watchpoint	: yes, count: 4, address/irw mask: [0x0ffc, 0x0ffc, 0x0ffb, 0x0ffb]
isa			: mips1 mips2 mips32r1 mips32r2
ASEs implemented	: mips16
shadow register sets	: 1
kscratch registers	: 0
package			: 0
core			: 0
VCED exceptions		: not available
VCEI exceptions		: not available
```

**Comment by pexcn** [comment]
试试用这两个 SDK:
https://downloads.openwrt.org/releases/19.07.4/targets/ath79/generic/openwrt-sdk-19.07.4-ath79-generic_gcc-7.5.0_musl.Linux-x86_64.tar.xz
https://downloads.openwrt.org/releases/19.07.4/targets/ar71xx/generic/openwrt-sdk-19.07.4-ar71xx-generic_gcc-7.5.0_musl.Linux-x86_64.tar.xz

**Comment by zeroly** [comment]
> 试试用这两个 SDK:
> https://downloads.openwrt.org/releases/19.07.4/targets/ath79/generic/openwrt-sdk-19.07.4-ath79-generic_gcc-7.5.0_musl.Linux-x86_64.tar.xz
> https://downloads.openwrt.org/releases/19.07.4/targets/ar71xx/generic/openwrt-sdk-19.07.4-ar71xx-generic_gcc-7.5.0_musl.Linux-x86_64.tar.xz

感谢！已经好了。
我的系统是18.06.2，我用了这个sdk：
https://downloads.openwrt.org/releases/18.06.2/targets/ar71xx/nand/openwrt-sdk-18.06.2-ar71xx-nand_gcc-7.3.0_musl.Linux-x86_64.tar.xz
