### ISSUE TITLE
最新版编译不过，出错。

### ISSUE THREAD

**Issue by openwrtdiy** [pexcn/openwrt-chinadns-ng#29]
OpenWrt-19.07.7

PKG_NAME:=chinadns-ng
PKG_VERSION:=1.0-beta.24
PKG_RELEASE:=3

PKG_SOURCE_PROTO:=git
PKG_SOURCE_URL:=https://github.com/zfl9/chinadns-ng.git
PKG_SOURCE_VERSION:=df3bb7c6310df9b3c0f874b7a0c38ea5ce0996cb
PKG_SOURCE:=$(PKG_NAME)-$(PKG_VERSION)-$(PKG_SOURCE_VERSION).tar.gz
PKG_SOURCE_SUBDIR:=$(PKG_NAME)-$(PKG_VERSION)-$(PKG_SOURCE_VERSION)
PKG_BUILD_DIR:=$(BUILD_DIR)/$(PKG_NAME)/$(PKG_SOURCE_SUBDIR)

PKG_BUILD_PARALLEL:=1
PKG_USE_MIPS16:=0

PKG_LICENSE:=GPL-3.0
PKG_LICENSE_FILES:=LICENSE
PKG_MAINTAINER:=pexcn <i@pexcn.me>

**Comment by openwrtdiy** [comment]
编译过程中出错信息如下：

make[4]: Entering directory '/home/kokang/openwrt-19.07.7/build_dir/target-x86_64_musl/chinadns-ng/chinadns-ng-1.0-beta.24-df3bb7c6310df9b3c0f874b7a0c38ea5ce0996cb'
x86_64-openwrt-linux-musl-gcc -std=c99 -Wall -Wextra -O3 -c chinadns.c -o chinadns.o
cc1: note: someone does not honour COPTS correctly, passed 0 times
x86_64-openwrt-linux-musl-gcc -std=c99 -Wall -Wextra -O3 -c dnsutils.c -o dnsutils.o
cc1: note: someone does not honour COPTS correctly, passed 0 times
x86_64-openwrt-linux-musl-gcc -std=c99 -Wall -Wextra -O3 -c dnlutils.c -o dnlutils.o
cc1: note: someone does not honour COPTS correctly, passed 0 times
x86_64-openwrt-linux-musl-gcc -std=c99 -Wall -Wextra -O3 -c netutils.c -o netutils.o
cc1: note: someone does not honour COPTS correctly, passed 0 times
x86_64-openwrt-linux-musl-gcc -std=c99 -Wall -Wextra -O3 -s -o chinadns-ng chinadns.o dnsutils.o dnlutils.o netutils.o
make[4]: Leaving directory '/home/kokang/openwrt-19.07.7/build_dir/target-x86_64_musl/chinadns-ng/chinadns-ng-1.0-beta.24-df3bb7c6310df9b3c0f874b7a0c38ea5ce0996cb'
touch /home/kokang/openwrt-19.07.7/build_dir/target-x86_64_musl/chinadns-ng/chinadns-ng-1.0-beta.24-df3bb7c6310df9b3c0f874b7a0c38ea5ce0996cb/.built
rm -rf /home/kokang/openwrt-19.07.7/build_dir/target-x86_64_musl/chinadns-ng/chinadns-ng-1.0-beta.24-df3bb7c6310df9b3c0f874b7a0c38ea5ce0996cb/.pkgdir/chinadns-ng.installed /home/kokang/openwrt-19.07.7/build_dir/target-x86_64_musl/chinadns-ng/chinadns-ng-1.0-beta.24-df3bb7c6310df9b3c0f874b7a0c38ea5ce0996cb/.pkgdir/chinadns-ng
mkdir -p /home/kokang/openwrt-19.07.7/build_dir/target-x86_64_musl/chinadns-ng/chinadns-ng-1.0-beta.24-df3bb7c6310df9b3c0f874b7a0c38ea5ce0996cb/.pkgdir/chinadns-ng
install -d -m0755 /home/kokang/openwrt-19.07.7/build_dir/target-x86_64_musl/chinadns-ng/chinadns-ng-1.0-beta.24-df3bb7c6310df9b3c0f874b7a0c38ea5ce0996cb/.pkgdir/chinadns-ng/usr/bin
install -m0755 /home/kokang/openwrt-19.07.7/build_dir/target-x86_64_musl/chinadns-ng/chinadns-ng-1.0-beta.24-df3bb7c6310df9b3c0f874b7a0c38ea5ce0996cb/chinadns-ng /home/kokang/openwrt-19.07.7/build_dir/target-x86_64_musl/chinadns-ng/chinadns-ng-1.0-beta.24-df3bb7c6310df9b3c0f874b7a0c38ea5ce0996cb/.pkgdir/chinadns-ng/usr/bin
install -m0755 /home/kokang/openwrt-19.07.7/build_dir/target-x86_64_musl/chinadns-ng/chinadns-ng-1.0-beta.24-df3bb7c6310df9b3c0f874b7a0c38ea5ce0996cb/chinadns-ng-update-list.sh /home/kokang/openwrt-19.07.7/build_dir/target-x86_64_musl/chinadns-ng/chinadns-ng-1.0-beta.24-df3bb7c6310df9b3c0f874b7a0c38ea5ce0996cb/.pkgdir/chinadns-ng/usr/bin
install: cannot stat '/home/kokang/openwrt-19.07.7/build_dir/target-x86_64_musl/chinadns-ng/chinadns-ng-1.0-beta.24-df3bb7c6310df9b3c0f874b7a0c38ea5ce0996cb/chinadns-ng-update-list.sh': No such file or directory
Makefile:68: recipe for target '/home/kokang/openwrt-19.07.7/build_dir/target-x86_64_musl/chinadns-ng/chinadns-ng-1.0-beta.24-df3bb7c6310df9b3c0f874b7a0c38ea5ce0996cb/.pkgdir/chinadns-ng.installed' failed
make[3]: *** [/home/kokang/openwrt-19.07.7/build_dir/target-x86_64_musl/chinadns-ng/chinadns-ng-1.0-beta.24-df3bb7c6310df9b3c0f874b7a0c38ea5ce0996cb/.pkgdir/chinadns-ng.installed] Error 1
make[3]: Leaving directory '/home/kokang/openwrt-19.07.7/package/app/openwrt-chinadns-ng'
time: package/app/openwrt-chinadns-ng/compile#1.40#0.65#179.76
package/Makefile:111: recipe for target 'package/app/openwrt-chinadns-ng/compile' failed
make[2]: *** [package/app/openwrt-chinadns-ng/compile] Error 2
make[2]: Leaving directory '/home/kokang/openwrt-19.07.7'
package/Makefile:107: recipe for target '/home/kokang/openwrt-19.07.7/staging_dir/target-x86_64_musl/stamp/.package_compile' failed
make[1]: *** [/home/kokang/openwrt-19.07.7/staging_dir/target-x86_64_musl/stamp/.package_compile] Error 2
make[1]: Leaving directory '/home/kokang/openwrt-19.07.7'
/home/kokang/openwrt-19.07.7/include/toplevel.mk:225: recipe for target 'world' failed
make: *** [world] Error 2
kokang@virtual-machine:~/openwrt-19.07.7$

**Comment by openwrtdiy** [comment]
如果换成原来这版本，编译可以成功。
PKG_NAME:=chinadns-ng
PKG_VERSION:=1.0-beta.24
PKG_RELEASE:=1

**Comment by pexcn** [comment]
现在应该可以了
