### ISSUE TITLE
chinadns-ng service fail to start

### ISSUE THREAD

**Issue by lizhuimu** [pexcn/openwrt-chinadns-ng#30]
I can run chinadns-ng using command line, such as '/usr/bin/chinadns-ng -b xxx -l xxx'. But I failed to run '/etc/init.d/chinadns-ng start'
I tried to figure out what was wrong by viewing /etc/init.d/chinadns-ng. In function start_chinadns_ng(), the variable $enable is set to 0, the script exited because of this.
I have no idea why $enable is 0. I am sure that I enabled chinadns-ng before staring it.
Please take a look at this situation when you have time, thanks.

**Comment by pexcn** [comment]
You should edit `/etc/config/chinadns-ng` and set `enable` to `1`.

**Comment by lizhuimu** [comment]
Problem solved. I need to learn more about how the openwrt services work. Thanks for the help!
