### ISSUE TITLE
建议不要使用个人网址提供的各种list文件

### ISSUE THREAD

**Issue by youkechat** [pexcn/openwrt-chinadns-ng#36]
rt

**Comment by youkechat** [comment]
一旦你网址疯了，大家还得修改一番

**Comment by youkechat** [comment]
另外建议luci增加从网址更新各种list功能

**Comment by pexcn** [comment]
本项目使用的是 GitHub 提供的源 https://github.com/pexcn/openwrt-chinadns-ng/blob/master/update-list.sh#L4-L7
