### ISSUE TITLE
给懒人减少搜寻的时间

### ISSUE THREAD

**Issue by PussAzuki** [pexcn/openwrt-chinadns-ng#5]
希望能直接在makefile里添加ipset依赖...不得不说，我还是编译完了，上机测试才发现op默认是没有ipset编译进去的...

**Comment by pexcn** [comment]
欢迎提交 pull request, 我对 openwrt 不是很熟悉，过几天有空再看看。

**Comment by PussAzuki** [comment]
谢谢
