### ISSUE TITLE
conffiles 的问题

### ISSUE THREAD

**Issue by pexcn** [pexcn/openwrt-chinadns-ng#7]
此处的配置是否无效？ https://github.com/pexcn/openwrt-chinadns-ng/blob/f5bd5d16fd2b5c460decd3eaeb7101d3517da87c/Makefile#L34-L38

这里的 postrm 似乎会在升级（卸载旧版本？）的时候执行
https://github.com/pexcn/openwrt-chinadns-ng/blob/f5bd5d16fd2b5c460decd3eaeb7101d3517da87c/Makefile#L52-L56

**Comment by PussAzuki** [comment]
conffiles那里看起来没问题？（根据pcap-dnsproxy的移植项目来看
postrm或许可以不需要？毕竟有些用户是用自己去搜集的路由表（例如我

**Comment by pexcn** [comment]
我是想让卸载这个软件包的时候，把 /etc/chinadns-ng 目录删掉

**Comment by PussAzuki** [comment]
让用户自己删好了（反正再安装也就多两个备份

**Comment by pexcn** [comment]
已修复。
当 `/etc/chinadns-ng` 目录发生变更的时候，里面的文件不会被删除，所以卸载的时候只删除空的 `/etc/chinadns-ng` 目录。
