### ISSUE TITLE
trust_dns 只能设置两个dns，更多就会出错，china_dns没试过

### ISSUE THREAD

**Issue by freeskyfly** [pexcn/openwrt-chinadns-ng#9]
trust_dns 设置两个dns，工作正常
设置三个dns，出现Instance chinadns-ng::chinadns-ng-3 s in a crash loop 6 crashes, 0 seconds since last crash
每次reload都会增加一条，loop 7，loop8，一直往上加。
我看了下，原版的chinadns-ng好像就是这样设置的。
不过相比之下，我在原来的chinadns上用了好多个dns地址.....

**Comment by freeskyfly** [comment]
测试了一下，针对，chinalist与gfwlist两个加速列表，采用chinadns-ng，由chinadns-ng进行判别，与通过dnsmasq进行判别，速度大概能差30-40ms左右。基本上接近于直接查询5353端口的速度。相比之下，原本通过dnsmasq进行判断，大概要增加40ms的延迟。

**Comment by pexcn** [comment]
根据 https://github.com/zfl9/chinadns-ng/blob/master/README.md, 可信 DNS 最多只能设置两个。
